development:
  adapter: postgresql
  encoding: utf8
  database: bookstore_dev
  pool: 5
  username: rails
  password: !QAZxsw2

test:
  adapter: postgresql
  encoding: utf8
  database: bookstore_test
  pool: 5
  username: rails
  password: !QAZxsw2

production:
  adapter: postgresql
  encoding: utf8
  database: bookstore
  username: rails
  password: !QAZxsw2
  pool: 5
  timeout: 5000
